// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using DG.Tweening;
using UniRx;

namespace QFramework.Tetris
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class UIGamePanelData : QFramework.UIPanelData
    {
    }
    
    public partial class UIGamePanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIGamePanelData ?? new UIGamePanelData();
            // please add init code here
            BtnPause.OnClickAsObservable().Subscribe(_ =>
            {
                StartHide();
                UIMgr.OpenPanel<UIHomePanel>(new UIHomePanelData()
                {
                    ShowRestartBtn = true
                });
            });
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {               

        }
        
        protected override void OnShow()
        {
            GameUI.Show();
            GameUI.DOAnchorPosY(-50f, 0.5f);
            CameraCtrl.Instance.ZoomIn();
            GameCtrl.Instance.StartGame();
        }

        public void StartHide()
        {
            GameUI.DOAnchorPosY(314f, 0.5f).OnComplete(() => { GameUI.Hide(); });
            GameCtrl.Instance.PauseGame();
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
