// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QFramework.Tetris
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIHomePanel
    {
        
        public const string NAME = "UIHomePanel";
        
        [SerializeField()]
        public Text LogoName;
        
        [SerializeField()]
        public RectTransform MenuUI;
        
        [SerializeField()]
        public Button BtnStart;
        
        [SerializeField()]
        public Button BtnRestart;
        
        [SerializeField()]
        public Button BtnSetting;
        
        [SerializeField()]
        public Button BtnRank;
        
        private UIHomePanelData mPrivateData = null;
        
        public UIHomePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIHomePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            LogoName = null;
            MenuUI = null;
            BtnStart = null;
            BtnRestart = null;
            BtnSetting = null;
            BtnRank = null;
            mData = null;
        }
    }
}
