// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Assetobj_prefab
    {
        public const string BundleName = "assetobj_prefab";
        public const string ASSETOBJ = "assetobj";
    }
    public class Shapes
    {
        public const string BundleName = "shapes";
        public const string SHAPE_1 = "shape_1";
        public const string SHAPE_2 = "shape_2";
        public const string SHAPE_3 = "shape_3";
        public const string SHAPE_4 = "shape_4";
        public const string SHAPE_5 = "shape_5";
        public const string SHAPE_6 = "shape_6";
        public const string SHAPE_7 = "shape_7";
    }
    public class Spriteatlas_spriteatlas
    {
        public const string BundleName = "spriteatlas_spriteatlas";
        public const string SPRITEATLAS = "spriteatlas";
    }
    public class Testimage_png
    {
        public const string BundleName = "testimage_png";
        public const string TESTIMAGE = "testimage";
    }
    public class Uiconnect_prefab
    {
        public const string BundleName = "uiconnect_prefab";
        public const string UICONNECT = "uiconnect";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "uigamepanel";
    }
    public class Uihomepanel_prefab
    {
        public const string BundleName = "uihomepanel_prefab";
        public const string UIHOMEPANEL = "uihomepanel";
    }
    public class Uimsg_prefab
    {
        public const string BundleName = "uimsg_prefab";
        public const string UIMSG = "uimsg";
    }
    public class Uitestunirx_prefab
    {
        public const string BundleName = "uitestunirx_prefab";
        public const string UITESTUNIRX = "uitestunirx";
    }
}
